name: Python Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests
        run: |
          python -m unittest discover

      - name: Run tests with coverage
        run: |
          pip install coverage
          coverage run -m unittest discover
          coverage report
          coverage xml

      - name: Test CLI functionality
        run: |
          python main.py addition 5 3
          python main.py soustraction 10 4
          python main.py multiplication 6 7
          python main.py division 20 5

  deploy:
    name: Vérification du déploiement
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Verify application functionality
        run: |
          echo "Vérification de la fonctionnalité de l'application..."
          # Exécutez des tests supplémentaires de l'application ici si nécessaire
          python main.py addition 10 20
          python main.py soustraction 30 15
          python main.py multiplication 5 5
          python main.py division 100 4

      - name: Generate summary
        run: |
          echo "## Résumé du déploiement" >> $GITHUB_STEP_SUMMARY
          echo "✅ L'application a été vérifiée avec succès" >> $GITHUB_STEP_SUMMARY
          echo "- La vérification a eu lieu à $(date)" >> $GITHUB_STEP_SUMMARY
          echo "- Branche: ${{ github.ref }}" >> $GITHUB_STEP_SUMMARY
          echo "- Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
